### ISSUE TITLE
Channel meta [feature request]

### ISSUE THREAD

**Issue by mm-tom** [khalwat/seomatic#13] opened 2016-01-13 15:19 UTC
Probably last suggestion, this is probably a bit more contentious I think - dismiss if I've got the wrong idea about usage :)

I really like the entry meta form, this is super useful for singles entries - but when looking to integrate in to a blog with many previous entries, it's not feasible to go through and assign blog fields to seomatic fields.
So in this scenario, I understand that what one would probably do is add to the twig template seomatic data, pulling in any entry fields to pass in to the meta data.

What I am imagining would be nice in this scenario though, is a page just like the entry meta form, where you can assign entry fields to seomatic fields, but on a channel-level. So, a way to edit the default field assignments on a per channel or section basis.
That way, when editing or creating an entry, the seomatic fields are already assigned with default assignments (and if they do not have a value, the subsequent available data set is used).

I've been using (and at times, writing) SEO plugins for Expression Engine and now Craft for a very long time now, I know how hard it can be to accommodate all the requirements across content types! I'm hoping my feedback is helpful.

Thanks again for awesome plugin! :)

**Comment by khalwat** [comment] 2016-01-13 17:56
So first, a preamble... which is that retrofitting a plugin like SEOmatic to a project is always going to be a little less clean than if it was designed to use it from the get-go.  It really is a different set of requirements for the plugin to be good at being retrofitted vs. being good at working out of the box in a new project.

That said, a few people have suggested the idea of "defaults" for the SEOmeta Meta FieldType.  I'm onboard, and like the idea.  Here's the problem.  Fields in Craft are their own little islands; they can exist in a dozen or more EntryType layouts.

So the global settings that you can assign to a field exist outside of the context of any Field Layout.  You can't (I know, I started to try) declare some settings that allow you pick one of the other fields in the Field Layout to pull from like you can do from within the Entry itself.

At best, what can be done is I display a popup menu of all sections, and than all Field Layouts where the field exists, the user picks one, and then they pick the field to pull from.  It's a little gross, and the other problem with this approach is because the settings are global, if that SEOmatic Meta field is included in two Field Layouts, then it's going to be defaulting them both to the same thing.  Which I think probably is never good.

That's why I stopped at implementing this; I'm trying to figure out a better way to do it, but failing.

**Comment by khalwat** [comment] 2016-01-13 19:32
As a solution for now, you can do what you want by using Twig to set your meta, something like this:

```
{% set seomaticMeta = { 
    seoTitle: entry.title,
    seoDescription: entry.summary,
    seoKeywords: extractKeywords(entry.body),
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: entry.title,
        description: entry.summary,
        image: seomaticMeta.twitter.image
    },
    og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: entry.title,
        description: entry.summary,
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

Put that in your blog template that `extends` your `layout.twig` (or whatever) that has the `{% hook 'seomaticRender' %}` in it, and it'll "just work", override all of your other meta.

I realize it's not ideal, but it's the easiest way to handle it on a site where you're retrofitting SEOmatic, as opposed to integrating it from the start.

**Comment by mm-tom** [comment] 2016-01-14 11:12
Ok, thanks for explaining the problem – and for the implementation tip. I really appreciate it :+1:

**Comment by davidhellmann** [comment] 2016-01-14 16:01
Hm :)

```

{% set seomaticMeta = seomaticMeta | merge({
  twitter: {
    image: previewImages[2].url
  }
}) %}
```

This works outside the `{% block foo %}` but when I set it within this block it doesn't work. 
Any Ideas?

**Comment by khalwat** [comment] 2016-01-14 18:52
@davidhellmann Yes, you'll need to do that outside of the `{% block %}` statements due to the way that Twig's processing order works:

https://straightupcraft.com/articles/twig-processing-order

Otherwise, you'll be setting the SEOmatic variables after the meta tags have already been rendered (so it won't do anything, effectively).

Also, you'll need do do the full array otherwise the other fields will get blown away, due to the way the Twig (poorly, imo) handles setting of arrays:

```
{% set seomaticMeta = seomaticMeta | merge({
    twitter: {
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.site,
        creator: seomaticMeta.twitter.creator,
        title: entry.title,
        description: entry.summary,
        image: previewImages[2].url
    }
}) %}
```

**Closed as completed** 2016-01-14 19:23 UTC
