### ISSUE TITLE
Javascript error in field.js

### ISSUE THREAD

**Issue by aelvan** [khalwat/seomatic#108] opened 2016-07-13 14:30 UTC
Still getting a javascript error on one of my sites. Not getting it on a new install, so I suspect something haven't been introduced correctly when I've upgraded seomatic on this one. Maybe uninstalling and installing seomatic would fix it, but there's a lot of content in this site and I don't want to loose it, so hope there's another solution.

The error in the console is:

`Uncaught TypeError: Cannot read property 'undefined' of undefined`

This happends on line 34 of field.js inside `setPreviewFields`. The boxes that are suppose to contain preview information in the field is empty.

I've tried logging `seomatic.options` on line 34, and it's an empty object. If I try to log `options` inside the constructor, it's `undefined`. 

I've tried saving the entry in question, same error. I've tried saving the section and the field in question, same error. 

Any idea what's happend here?

**Comment by khalwat** [comment] 2016-07-13 15:59
I'm on vacation atm, but I will look into it when I get back.  Basically what it's doing is in the FieldType it is building a list of the field handles and their data, so that it can do a swap to supply a "preview" of that field when you select it.

For some reason, there's a field that has no key/value pair in the array for this preview.  Which is really weird.  What kinds of fields are in that Entry?  Anything custom?

**Comment by aelvan** [comment] 2016-07-14 11:44
In some of the entry types I'm using Venti and Link-it fields. But I'm getting the same error on some entry types where I have nothing except input fields and textareas. 

If I log `element` in the constructor, it's the seomatic field itself that's returned. 

But, not urgent, have a look at it when you're back from vacation. Have a nice one! :)

**Comment by khalwat** [comment] 2016-08-19 17:14
Fixed, apparently.

**Comment by danieltott** [comment] 2016-08-24 14:10
I am getting this exact error in devmode (not production). Further, the two "Preview SEO" tabs do nothing. On production, with the same data, there is no error and the preview panels work fine.

**Comment by khalwat** [comment] 2016-08-24 16:52
@danieltott Are you saying that neither the Preview SEO Meta Tags or Preview SEO Meta Display buttons are working?

If so, something sounds wrong/incomplete with your install.

**Comment by danieltott** [comment] 2016-08-24 18:18
Yes - that's what I'm saying. On the same entry page that is giving me that error in the JS console:

![image](https://cloud.githubusercontent.com/assets/360261/17942242/9513494e-6a04-11e6-8117-6fc167a0ed20.png)

![image](https://cloud.githubusercontent.com/assets/360261/17942314/d04e00b2-6a04-11e6-8639-008f2dba01ee.png)

This is on my local dev machine, but on production I'm not getting this error so I'm not really sure what is going on. I just did a full mysql dump from production and wiped out my local db and storage, redownloaded seoMatic (just to be sure), and I'm still getting this error locally. I discovered it while trying to figure out #129.

**Comment by danieltott** [comment] 2016-08-24 18:20
So you can see it's set to use the Hero Image field. Here's the field values in the entry:

![image](https://cloud.githubusercontent.com/assets/360261/17942539/d1e4cfae-6a05-11e6-887d-183d42bcac9d.png)

That image in the screenshot is correct, it's just the output that is not correct

**Comment by ClemensSchneider** [comment] 2016-09-02 12:31
We're seeing the exact same error in field.js:34

![image](https://cloud.githubusercontent.com/assets/1398168/18203762/461f9920-7119-11e6-9a1d-cca82e5acab8.png)

Happens with both devMode enabled and disabled...

**Comment by ClemensSchneider** [comment] 2016-09-06 21:07
@danieltott Which version of PHP do you use on your local dev machine? I noticed that this bug occurs when using `5.5.3` but not when using `5.6.19` or `7.0.4`.

**Comment by khalwat** [comment] 2016-09-09 01:58
So can anyone confirm that this is fixed in version 1.1.36 of SEOmatic?

**Comment by danieltott** [comment] 2016-09-09 16:30
@ClemensSchneider I was indeed using `5.5.3`, however @khalwat the issue is not happening anymore upon updating

**Comment by ClemensSchneider** [comment] 2016-09-09 17:10
It's resolved for me, too. Was related to #132

**Comment by khalwat** [comment] 2016-09-09 22:06
Great!  That explains why it only sporadically happens.  Thanks for your help.

**Closed as completed** 2016-09-09 22:09 UTC
