### ISSUE TITLE
Double quotes are not escaped

### ISSUE THREAD

**Issue by benface** [khalwat/seomatic#262] opened 2017-07-17 02:31 UTC
If you have double quotes in your `seomaticMeta.seoDescription`, for instance, they are rendered unescaped because of the `|raw` filter, which breaks the HTML.

**Comment by khalwat** [comment] 2017-07-26 02:58
hmmm. They really should be escaped, though, because they are run through `sanitizeArray()` which does:

                $value = htmlspecialchars($value, ENT_COMPAT | ENT_HTML401, 'UTF-8', false);

http://php.net/manual/en/function.htmlspecialchars.php

**Comment by khalwat** [comment] 2017-07-26 03:03
In my test, they are rendered as expected:




    
    <title>[devMode] nystudio107 | &quot;Making&quot; Websites Better through Accessibility</title>
    <meta name="dcterms.Title" content="&quot;Making&quot; Websites Better through Accessibility" />
    <meta property="og:title" content="nystudio107 | &quot;Making&quot; Websites Better through Accessibility" />
 
etc.

**Comment by benface** [comment] 2017-07-26 17:21
@khalwat What about the site's SEO description? I can reproduce it easily by using double quotes in there:

In the CP:
<img width="692" alt="screen shot 2017-07-26 at 1 19 21 pm" src="https://user-images.githubusercontent.com/1059139/28634431-2bfa3558-7205-11e7-9372-24cbe41b94d6.png">

In Safari's dev tools:
<img width="356" alt="screen shot 2017-07-26 at 1 19 59 pm" src="https://user-images.githubusercontent.com/1059139/28634430-2bf8aaa8-7205-11e7-82c3-66eef4af40e8.png">

**Comment by benface** [comment] 2017-08-02 15:32
Hey @khalwat I was able to find how to reproduce this. If you add
```
{% set seomaticTemplatePath = '_seo_meta' %}
```
just above
```
{% hook 'seomaticRender' %}
```
and make an exact copy of `craft/plugins/seomatic/templates/_seo_meta.twig` in `craft/templates`, the double quotes are not escaped. I have made a sample project illustrating this issue to save you time, if needed (includes SQL dump): https://benface.com/files/seomatic-bug.zip

Thank you!

**Comment by khalwat** [comment] 2017-08-02 15:46
Can you reproduce it *without* that `{% set seomaticTemplatePath = '_seo_meta' %}` line?

**Comment by benface** [comment] 2017-08-02 15:47
No, I cannot; sorry for not isolating the issue better in the first place.

**Comment by khalwat** [comment] 2017-08-02 15:55
This is fixed by the build checked into `develop`

Thanks @benface

**Closed as completed by khalwat** 2017-08-02 15:55 UTC
