### ISSUE TITLE
Leaving Entry with Seomatic Field Prompts "Do you want to leave this site?"

### ISSUE THREAD

**Issue by AbbeyDesign** [khalwat/seomatic#319] opened 2018-02-06 23:28 UTC
This is on Mac - all browsers. Craft CMS 2.6.3007 SEOmatic 1.1.56

The message is slightly different per browser but leaving or refreshing an entry page in the CP that contains a SeoMatic field prompts a "Do you want to leave this site?" message.

I have had this issue before in the past but with other fields(dropdowns/neo). I narrowed it down to seomatic because channels that do not have this field do not show the message. If I add the field to a channel it starts doing it. Removing it stops the behavior.

Don't know if this is related, but here is a thread where I had the same issue with another field.
https://github.com/benjamminf/craft-neo/issues/45

**Comment by khalwat** [comment] 2018-02-06 23:47
SEOmatic does not explicitly put up this message; I'm not sure what the FieldType could be doing that would trigger Craft to mark it as "dirty", but I've yet to see it happen.

I tried to reproduce this on `Craft CMS 2.6.3003` but was unable to.  Perhaps it's some kind of change/regression in `Craft CMS 2.6.3007`?

I navigated to an entry that had an SEOmatic field, and then hit the Back button, and received no warning.

**Comment by AbbeyDesign** [comment] 2018-02-06 23:55
Let me look at an older site with seomatic if I can find one. It definitely started in the last couple of weeks.

**Comment by AbbeyDesign** [comment] 2018-02-07 00:00
Craft CMS 2.6.3000 and SEO 1.1.56 does not do it

**Comment by khalwat** [comment] 2018-02-08 15:26
So I confirmed that this happens in the latest Craft 2.x Craft CMS 2.6.3008. I'm not sure what is causing it, but I changed nothing in SEOmatic, and it started happening with a recent update (I'm suspecting 2.6.3008).

So it's either a Craft regression, or something I'm doing wrong that only now is bubbling to the surface.

**Comment by xo-dev** [comment] 2018-02-08 18:01
Just FYI, we did not see this behavior in any of our Craft CMS 2.6.3004 installs, but from Version 2.6.3007 up.

**Comment by khalwat** [comment] 2018-02-08 18:47
Interestingly, if you have the SEOmatic field in a separate tab, it only happens if you _do_ switch to that tab.

**Comment by AbbeyDesign** [comment] 2018-02-08 18:53
I actually don't get that particular behavior... I get the warning if seomatic is on a tab, if I have visited the tab or not, or if seomatic is not on a tab at all.

**Comment by MattWilcox** [comment] 2018-02-09 09:02
We've been seeing this on a bunch of projects since each of them upgraded to Craft 2.6.3007 or 3008. I don't think we had it with versions of Craft before then. They did update jQuery and the Migrate plugin in 3006 which might have something to do with it?

We have the SEOmatic field in a separate tab on all our projects, and we do not have to switch to the SEOmatic tab first in order to trigger this behaviour. Simply loading the Entry and then trying to navigate away causes it.

**Comment by khalwat** [comment] 2018-02-09 13:51
So @MattWilcox you're exactly right. I've been discussing this with Brad @ P&T and it appears that it is indeed related to the switch over to jQuery and the Migrate plugin , which is what I was suspecting.

Basically, I do some setup via jQuery in `$(function () {` which is just a shortcut for `$(document).ready()`. Apparently somehow this is now happening _after_ Craft serializes the DOM, which is why it thinks things have changed.

Right now, I'm not sure whether or not this is something that I need to try to fix, or whether they will be fixing it (it's possible their changes affect other plugins as well).

**Comment by MattWilcox** [comment] 2018-02-09 17:27
Well, good news that the problem has been tracked down. Hopefully the resolution won't be too painful. We've been holding off on running updates on live projects for fear of having to tell all our clients to ignore the pop-up. A bad thing to be teaching clients.

**Comment by khalwat** [comment] 2018-02-13 18:37
Looks like it's something that P&T is addressing: https://github.com/craftcms/cms/commit/781da63270b1254746b4fb91b63716a915b4f2ff

**Comment by khalwat** [comment] 2018-02-13 23:08
Fixed in Craft 2.6.3009 https://craftcms.com/changelog#2-6-3009

**Closed as completed by khalwat** 2018-02-13 23:08 UTC
