### ISSUE TITLE
Getting Template Error

### ISSUE THREAD

**Issue by sg-modlab** [khalwat/seomatic#4] opened 2015-12-29 12:51 UTC
Here is the template error I am getting:

![image](https://cloud.githubusercontent.com/assets/529067/12034566/9e8cb836-ae00-11e5-90d8-013fc3643c01.png)

In admin I have the Twitter handle populated and saved which I believe maps to the Twitter creator no?

![image](https://cloud.githubusercontent.com/assets/529067/12034576/c0beea82-ae00-11e5-9f01-20f7c76a9f6b.png)

Interestingly I am not getting this in my dev env. I am getting this after I deployed to our staging server to test.

**Comment by khalwat** [comment] 2015-12-29 17:20
Okay, so the issue is that the `twitter:creator` tag is only used if you're using the `twitter:card` of type `summary_large_image` (their spec, not mine).

I think a better way for me to handle it would be to just set it to `''` if you're not using `summary_large_image`.  I just pushed a fix for you:

https://github.com/khalwat/seomatic

It just sets it to an empty string (which will cause the tag to not be rendered) for card types that don't use it.

**Closed as completed** 2015-12-29 17:30 UTC

**Comment by sg-modlab** [comment] 2015-12-29 17:39
Confirmed ty
