### ISSUE TITLE
Config option to override/disallow robots per environment

### ISSUE THREAD

**Issue by michaelroper** [khalwat/seomatic#119] opened 2016-08-10 06:30 UTC
Feature request as discussed - would be great to have the ability to pass a config variable that would allow you to disallow all robots for a particular environment, eg so that a staging site that might be publicly accessible does not get indexed by search engines.

**Comment by khalwat** [comment] 2016-08-12 20:29
Let's do one better:

```
/**
 * This allows you to globally override the meta settings on your website.  WARNING:
 * anything you set here will REPLACE the meta settings globally.  You might wish to
 * use this, for instance, to set 'robots' to be 'none' on development/staging to
 * prevent crawlers from indexing it.  Since this config file is multi-environment aware,
 * like any Craft config file, this allows you to do just that.
 * Leave any value in the array blank to cause it to not override.
 */

    "globalMetaOverride" => array(
        'locale'                    => '',
        'seoMainEntityCategory'     => '',
        'seoMainEntityOfPage'       => '',
        'seoTitle'                  => '',
        'seoDescription'            => '',
        'seoKeywords'               => '',
        'seoImageTransform'         => '',
        'seoFacebookImageTransform' => '',
        'seoTwitterImageTransform'  => '',
        'twitterCardType'           => '',
        'openGraphType'             => '',
        'robots'                    => '',
        'seoImageId'                => '',
    ),
```

**Comment by khalwat** [comment] 2016-08-12 20:37
Checked into `develop`:

[Added] Added a 'globalMetaOverride' setting to config.php

https://github.com/nystudio107/seomatic/tree/develop

**Closed as completed by khalwat** 2016-08-12 20:37 UTC
Labels: Feature Request

**Comment by siebird** [comment] 2017-06-20 17:34
Andrew, 

Just realized this was not a default–I assumed it was. 

However, I thought this would be a safe default for the plugin's robots.txt settings as all my site (and I would assume most others) define `devMode` in the `config.php` settings. And then allow users to further customize with the `globalMetaOverride`.

```# robots.txt for {{ siteUrl }}
Sitemap: {{ siteUrl }}sitemap.xml
{% switch craft.config.devMode %}
	{% case "1" %}
# devMode - disallow all
User-agent: *
Disallow: /
	{% default %}
# Live - don't allow web crawlers to index Craft
User-agent: *
Disallow: /craft/
{% endswitch %}
```

**Comment by khalwat** [comment] 2017-06-20 17:36
Well, it's kind of arguable how to handle it @siebird -- the problem is that everyone handles multi-environment configs differently.

I did write up an article on how to do it with SEOmatic, though: 

https://nystudio107.com/blog/prevent-google-from-indexing-staging-sites

**Comment by siebird** [comment] 2017-06-20 17:38
I agree–thought it was safe default rather than having to go in everytime to edit that setting.

Re: article, that's where I got it from and modified as I don't use multi-environment settings where `live|staging|local` are set.

**Comment by khalwat** [comment] 2017-06-20 17:38
Gotcha, I guess you're right, that would be a safe default to use.

**Comment by khalwat** [comment] 2017-06-20 18:12
Okay here's what I will be using for the default going forward:

```
# robots.txt for {{ siteUrl }}
# For a multi-environment setup, see: https://nystudio107.com/blog/prevent-google-from-indexing-staging-sites

Sitemap: {{ siteUrl |trim('/') }}/sitemap.xml

{% if craft.config.devMode %}
# devMode - disallow all

User-agent: *
Disallow: /
{% else %}
# Live - Don't allow web crawlers to index Craft

User-agent: *
Disallow: /craft/
{% endif %}
```

**Comment by siebird** [comment] 2017-06-20 19:41
Nice!
