### ISSUE TITLE
Facebook and Twitter image is empty

### ISSUE THREAD

**Issue by espensgr** [khalwat/seomatic#138] opened 2016-09-07 07:19 UTC
I have a picture in the SEO image field and nothing in Facebook and Twitter image. But the og:image tag is empty. and the twitter image is empty in the Meta Template Variables.

```
{% set seomaticMeta = { 
    "seoTitle": "Perspektiv på kundeorientering",
    "seoDescription": " Det finnes mange vedtatte sannheter her i verden; du skal ha en vanntett forretningsplan, digitaliseringen kommer og tar deg og kunde/markedsorientering er…",
    "seoKeywords": "skal være, bare være, verden lettere, være, skal vi være, verden, skal, blir, bare, tenke, blir det lettere, verdi, tror, lettere, setter",
    "seoImage": "https://mustasj.no/dynamic/upload/bilder/meny2000.jpg",
    "robots": "",
    "canonicalUrl": "https://mustasj.no/playground/perspektiv-på-kundeorientering",
    "twitter": { 
        "card": "summary_large_image",
        "site": "@mustasj",
        "creator": "@mustasj",
        "title": "Perspektiv på kundeorientering | Mustasj",
        "description": " Det finnes mange vedtatte sannheter her i verden; du skal ha en vanntett forretningsplan, digitaliseringen kommer og tar deg og kunde/markedsorientering er…",
        "image": ""
    },
    "og": { 
        "type": "article",
        "locale": "nb_no",
        "url": "https://mustasj.no/playground/perspektiv-på-kundeorientering",
        "title": "Perspektiv på kundeorientering | Mustasj",
        "description": " Det finnes mange vedtatte sannheter her i verden; du skal ha en vanntett forretningsplan, digitaliseringen kommer og tar deg og kunde/markedsorientering er…",
        "image": "",
        "site_name": "Mustasj",
        "see_also": ["https://twitter.com/mustasj","https://www.facebook.com/mustasj","https://plus.google.com/104248222092439841518"]
    },
    "article": { 
        "author": "https://www.facebook.com/mustasj",
        "publisher": "https://www.facebook.com/mustasj",
        "tag": ["skal være","bare være","verden lettere","være","skal vi være","verden","skal","blir","bare","tenke","blir det lettere","verdi","tror","lettere","setter"],
        "modified_time": "2016-09-07T07:16:42+0000",
        "published_time": "2016-08-25T22:00:00+0000"
    },
    "breadcrumbs": { 
        "Forside": "https://mustasj.no/",
        "Perspektiv på kundeorientering": "https://mustasj.no/playground/perspektiv-på-kundeorientering"
    }
} %}
```

Also when i set up the seomatic field i turned of facebook and twitter image changeable but they still show up on the entry. And the Facebook OpenGraph Image Source Changeable dont get saved at all. So it is still on in the field settings. Here is a screenshot of the admin [after save](https://www.dropbox.com/s/g9vh8293c3wti1b/Skjermbilde%202016-09-07%2009.13.17.png?dl=0) on the field type.

[Here](https://www.dropbox.com/s/hexkzijuo7ngfzp/Skjermbilde%202016-09-07%2009.15.57.png?dl=0) is a screenshot on an entry with the field, and the fields still show up.

**Comment by khalwat** [comment] 2016-09-07 07:21
This is fixed in SEOmatic 1.1.36.

https://github.com/nystudio107/seomatic

**Closed as completed by khalwat** 2016-09-07 07:21 UTC

**Comment by espensgr** [comment] 2016-09-07 07:52
The first issue is fixed in that update, but not the second part.

**Comment by khalwat** [comment] 2016-09-07 18:53
So the second issue is not a bug.  From the screenshot, it's working as expected.

The "changeable" setting refers to the `source`, not the image itself.
