### ISSUE TITLE
If no Facebook ID you get a template error

### ISSUE THREAD

**Issue by sg-modlab** [khalwat/seomatic#3] opened 2015-12-29 02:09 UTC
Using the `{% set seomaticMeta = { ... } %}` template tag, I was getting an error about using `og` array. Found through a little trial and error that the issue is because I did not have a Facebook ID in my SEOMatic Social Media area set in CP. 

Is there a reason that is required? I believe OG data can be useful without it. If it is required, seems a friendlier message or someway to know that is required for OG data would be helpful.

**Comment by khalwat** [comment] 2015-12-29 03:51
Where were you getting these errors?  Can you post what the error was? Using the Open Graph Testing Tool, do you mean?

**Comment by sg-modlab** [comment] 2015-12-29 04:04
Template rendering error. Testing tool mentioned I had no Facebook ID set for open graph which was my lead to try to put one.

**Comment by khalwat** [comment] 2015-12-29 04:06
Forgive me, I'm trying to reproduce the error so I can fix it.  I put this in my template:

```
{% set seomaticMeta = { 
    seoTitle: "This is the default global title of the site pages.",
    seoDescription: "This is the default global natural language description of the content on the site pages.",
    seoKeywords: "This is the default global list of comma-separated key words that are relevant to the content on the site pages.",
    seoImage: "",
    canonicalUrl: "http://nystudio107.dev/",
    twitter: { 
        card: "summary",
        site: "@nystudio107",
        title: "This is the default global title of the site pages. | nystudio107",
        description: "This is the default global natural language description of the content on the site pages.",
        image: ""
    },
    og: { 
        type: "website",
        locale: "en",
        url: "http://nystudio107.dev/admin/seomatic/social/en",
        title: "This is the default global title of the site pages. | nystudio107",
        description: "This is the default global natural language description of the content on the site pages.",
        image: "",
        site_name: "nystudio107",
        see_also: ["https://twitter.com/nystudio107"]
    }
} %}
```

...and made sure that the Facebook Profile ID field in SEOmatic's Social Media settings is blank.  I didn't get a template error... can you post the template error you were getting, or the steps to reproduce?

**Comment by sg-modlab** [comment] 2015-12-29 12:28
This is what I used on our blog following the docs

```
{% set seomaticMeta = { 
    seoTitle: "Some Title",
    seoDescription: entry.summary,
    seoKeywords: "Some,Key,Words",
    seoImage: seomaticMeta.seoImage,
    canonicalUrl: entry.url,
    twitter: { 
        card: seomaticMeta.twitter.card,
        site: seomaticMeta.twitter.card,
        creator: seomaticMeta.twitter.creator,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.twitter.image
    },
    og: { 
        type: seomaticMeta.og.type,
        locale: seomaticMeta.og.locale,
        url: entry.url,
        title: "Some Title",
        description: entry.summary,
        image: seomaticMeta.og.image,
        site_name: seomaticMeta.og.site_name,
        see_also: seomaticMeta.og.see_also
    }
} %}
```

**Comment by khalwat** [comment] 2015-12-29 17:21
So the issue here was that I wasn't filling in the `og` array if you had no Facebook Profile ID set.  Which is probably not right, because as you note, you can use the `og:` tags even without a Facebook Profile ID set (though it's better if it is set).

I pushed a fix for you:

https://github.com/khalwat/seomatic

**Closed as completed by khalwat** 2015-12-29 17:21 UTC

**Comment by sg-modlab** [comment] 2015-12-29 17:35
Great, checking out now

**Comment by sg-modlab** [comment] 2015-12-29 17:39
Confirmed, ty
